services:
  # 1. DATABASE
  mysqldb:
    image: mysql:8.0
    container_name: tmt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@Thanhquynh170456"
      MYSQL_DATABASE: dogiadung_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. BACKEND
  server:
    build: ./server
    container_name: tmt_server
    restart: always
    ports:
      - "8081:8081"
    env_file:            
      - ./server/.env
    environment:         
      - DB_HOST=mysqldb 
    depends_on:
      - mysqldb

  # 3. FRONTEND
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: tmt_client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8081
    depends_on:
      - server

volumes:
  mysql_data: